### ISSUE TITLE
Bug: python connection close will crash 

### ISSUE THREAD

**Issue by min-mwei** [kuzudb/kuzu#3720] opened 2024-06-27 16:59 UTC
### Kùzu version

v0.4.2

### What operating system are you using?

Ubuntu 22.04

### What happened?

The following code would crash the process when close is called. 

```
import kuzu

db_path='acme'
#db = kuzu.Database(database_path=db_path)
db = kuzu.Database(db_path)
conn = kuzu.Connection(db)
ddl = """
create node table MSEntraRESTCall (objectId string,requestTime timestamp,uri string,uriScheme string,uriHost string,resourcePath string,httpMethod string,respons
eStatusCode int64,ipAddress string,targetObjectIds string,internalCorrelationId string,correlationId string,tenantId string,domainName string,operationName strin
g,appId string,appServicePrincipalId string,resourceAppId string,identityId string,identityType string,selectedProperties string,filteredProperties string,change
dProperties string,uniqueTransactionId string,requestIdFromUti string,primary key(objectId));
"""
ret = conn.execute(ddl)
conn.close()
db.close()
```

**Comment by prrao87** [comment] 2024-06-27 19:06
@min-mwei I've seen this same issue come up elsewhere too - may I know the use case for closing the connection explicitly as you did here? The current approach in the Python client is to follow DuckDB's approach, where explicitly closing the connection is not necessary.

**Comment by mewim** [comment] 2024-06-27 19:14
I can reproduce this on Ubuntu 22.04 locally. It seems to cause a `Segmentation fault`. I will look into it.

**Comment by min-mwei** [comment] 2024-06-27 21:20
@prrao87 the use case is to run kuzu on the "server side", assume closing the connection is one way to reuse resources especially there are "close API" for both Connection and Database

**Comment by acquamarin** [comment] 2024-07-01 05:23
I think the issue is related to the query result deletion.
QueryResult is stored in a factorizedTable whose memory is managed by the bufferManager(database component).
If we destroy the database before deleting the query result, `Segmentation fault.` occurs when python deletes the queryResult.
The simplest work around is to always delete queryResults before deleting conneciton and database.
simply add `del ret` before the
```
conn.close()
db.close()
```
call

**Comment by mewim** [comment] 2024-07-01 14:39
> I think the issue is related to the query result deletion. QueryResult is stored in a factorizedTable whose memory is managed by the bufferManager(database component). If we destroy the database before deleting the query result, `Segmentation fault.` occurs when python deletes the queryResult. The simplest work around is to always delete queryResults before deleting conneciton and database. simply add `del ret` before the
> 
> ```
> conn.close()
> db.close()
> ```
> 
> call

@min-mwei, we also have a `QueryResult.close()` method: https://kuzudb.com/api-docs/python/kuzu.html#QueryResult.close

Calling `ret.close()` before closing the connection and database should fix it. It is a bit safer than deleting `ret`.

**Closed** 2024-07-02 12:42 UTC
Labels: bug
