### ISSUE TITLE
`REL TABLE GROUP`: Error: Binder exception: Create rel  with multiple rel labels or bound by multiple node labels is not supported.

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2677] opened 2024-01-17 12:37 UTC
Version: v0.1.0

`REL TABLE GROUP` seems not equivalent to separately defined `REL`s.

This errors:
```cypher
CREATE NODE TABLE V1 (id STRING, PRIMARY KEY(id));
CREATE NODE TABLE V2 (id STRING, PRIMARY KEY (id));
CREATE NODE TABLE V3 (id STRING, PRIMARY KEY (id));
CREATE REL TABLE GROUP MYREL(FROM V3 TO V2, FROM V2 TO V1);

kuzu> CREATE (:V3 {id: "v3"})-[:MYREL]->(:V2 {id: "v2"})-[:MYREL]->(:V1 {id: "v1"});
Error: Binder exception: Create rel  with multiple rel labels or bound by multiple node labels is not supported.
```

This works:
```cypher
CREATE NODE TABLE V1 (id STRING, PRIMARY KEY(id));
CREATE NODE TABLE V2 (id STRING, PRIMARY KEY (id));
CREATE NODE TABLE V3 (id STRING, PRIMARY KEY (id));
CREATE REL TABLE RELV2V1(FROM V2 TO V1);
CREATE REL TABLE RELV3V2(FROM V3 TO V2);
CREATE (:V3 {id: "v3"})-[:RELV3V2]->(:V2 {id: "v2"})-[:RELV2V1]->(:V1 {id: "v1"});
```

**Comment by andyfengHKU** [comment] 2024-01-17 14:04
Hi @sapalli2989, this is intended behaviour. `REL GROUP` is a syntactic sugar representing union of multiple relationship tables with the same set of properties. During compilation, we will expand `REL GROUP` as the union of its `REL tables`. So `REL GROUP` is not a physical table where data can be inserted.

We don't support inserting node or relationship with multiple labels because the semantic will be inconsistent with Neo4j. In Neo4j v4, `CREATE (v:A:B)` will create a vertex with label `A AND B` while if Kùzu were to support `CREATE (v:A:B)`, we will create one vertex with label `A` and another vertex with label `B`.

I believe in Neo4j v5, they start to use `CREATE (v:A&B)` and `CREATE (v:A|B)` to differentiate the `AND/OR` label semantic. We wanna first evaluate how practical it is to comply to Neo4j v5 semantic.

So in current version of Kùzu, we do not allow insert node/relationship with multiple label to avoid ambiguity.

**Comment by andyfengHKU** [comment] 2024-01-18 09:56
Hi @sapalli2989 

> Wouldn't you think, it makes sense to make CREATE consistent with MATCH regarding REL TABLE GROUP

This is indeed what we are aiming to achieve. I believe after PR #2680 the following query will execute successfully as you suggested since we are able to resolve label from context.
```
CREATE (:V3 {id: "v3"})-[:MYREL]->(:V2 {id: "v2"})
```

The failure case would be 
```
CREATE ({id: "v3"})-[:MYREL]->({id: "v2"})
```
because we cannot infer to which label/table we are inserting `v3`, `v2` and the edge between them. And as we mentioned above, we don't want to insert to all possible labels/tables because that will lead to a different semantic against Neo4j.

> I rather thought of it as a simple grouping mechanism for relationships with the same generic name (like :IS, :HAS), so I don't need to create and remember several relationship names. 

I think this is a correct understanding and will always work for `MATCH`. For `CREATE`, it works if we can resolve insertion to a particular label/table.

**Comment by sapalli2989** [comment] 2024-01-20 16:46
> This is indeed what we are aiming to achieve.

Great! Inference of labels from context for `CREATE` makes a lot of sense and will make `REL GROUP` much more viable and consistent with `MATCH`.

> I think this is a correct understanding and will always work for MATCH. For CREATE, it works if we can resolve insertion to a particular label/table.

Yes, main confusion was due to the mismatch between `CREATE` and `MATCH` for `REL GROUP`.

**Closed** 2024-01-23 06:32 UTC
