### ISSUE TITLE
Bug: CREATE NODE TABLE IF NOT EXISTS error

### ISSUE THREAD

**Issue by teetering** [kuzudb/kuzu#3988] opened 2024-07-30 19:32 UTC
### Kùzu version

Latest

### What operating system are you using?

MacOS 14.5

### What happened?

Documentation gives the following example:
```
CREATE NODE TABLE IF NOT EXISTS UW(ID INT64, PRIMARY KEY(ID))
```
However, if I actually try it I get:
```
Error: Parser exception: mismatched input 'NOT' expecting '(' (line: 1, offset: 21)
"CREATE NODE TABLE IF NOT EXISTS UW(ID INT64, PRIMARY KEY(ID))  "
                      ^^^
```

**Comment by andyfengHKU** [comment] 2024-07-30 19:37
hi @teetering, does the `latest` mean `v0.4.2`.

`IF NOT EXISTS` is a feature we add in `v0.5.0` which should be available two days from now. Someone must have updated the documentation unexpectedly.

**Comment by prrao87** [comment] 2024-07-30 19:48
Hi @teetering, yes, apologies for the lookahead docs in this case - this should have only been merged in our docs once we make our 0.5.0 release (in a couple days from now). Until we announce the 0.5.0 release shortly, you can use our dev build via `pip install --pre kuzu` and see that this functionality works as intended. Once 0.5.0 is out, you can switch to the stable release.

**Closed by prrao87** 2024-07-30 19:48 UTC

**Comment by teetering** [comment] 2024-07-31 18:42
Thank you for the response. FWIW, part of the reason that I didn't know my version is that typing `kuzu -v` isn't working for  the most recent release (presumably v0.4.2) on MacOS. Will play with the dev build for now.

**Comment by prrao87** [comment] 2024-08-01 01:26
Thanks for your patience! We'll be making the release for 0.5.0 likely Friday :)
