### ISSUE TITLE
Queries that cause Kuzu to segfault.

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#2687] opened 2024-01-18 16:31 UTC
Here are some of the queries I found that cause Kuzu to segfault:
```
MATCH (tab0:tab0) WHERE tab0.col3 <= 50 AND EXISTS { MATCH (in_select_tab0:tab0) WHERE tab0.col3 = in_select_tab0.col0 AND (in_select_tab0.col0 = 307) AND EXISTS { MATCH (in_select_tab0:tab0) WHERE in_select_tab0.col0 = in_select_tab0.col3 AND (((in_select_tab0.col3 > 437)) AND in_select_tab0.col4 >= 364.33) } AND in_select_tab0.col1 <= 749.88 AND in_select_tab0.col4 > 248.44 OR (in_select_tab0.col0 >= 492) AND (in_select_tab0.col0 >= 673) } OR (tab0.col3 <= 465 OR ((tab0.col1 >= 428.17 AND tab0.col1 <= 578.38))) RETURN tab0.pk;
MATCH (tab0:tab0) WHERE ((tab0.col0 >= 64)) AND tab0.col0 > 88 OR tab0.col0 IS Null AND (((((((tab0.col1 = 64.87 OR tab0.col1 = 50.15 OR tab0.col1 = 55.44 OR tab0.col1 = 96.63 OR tab0.col1 = 90.84)))) OR ((tab0.col3 < 39))))) AND tab0.col1 = 14.23 OR (tab0.col3 > 23) OR tab0.col4 IS Null AND tab0.col1 > 33.73 AND tab0.col1 = 42.62 AND (((tab0.col1 <= 79.77) AND ((tab0.col4 <= 8.8) AND tab0.col0 > 1 OR (tab0.col1 = 88.91 OR tab0.col1 = 10.57 OR tab0.col1 = 31.93) AND tab0.col4 = 36.83 AND ((((tab0.col0 < 88)) AND tab0.col3 <= 9 AND tab0.col0 > 73 AND tab0.col0 <= 74 AND (tab0.col4 > 92.51) OR (tab0.col4 < 49.85 AND (tab0.col0 >= 59) OR tab0.col1 >= 11.36 AND tab0.col3 < 8 AND tab0.col3 > 87 AND (tab0.col3 > 76) AND tab0.col0 <= 86 AND tab0.col0 > 33 AND tab0.col3 IS Null OR tab0.col3 > 3 AND tab0.col0 <= 97 OR (tab0.col1 >= 65.52) AND tab0.col0 <= 0 AND tab0.col4 < 54.21 AND tab0.col3 > 71 OR tab0.col1 > 21.40) OR (tab0.col0 <= 64 OR tab0.col0 >= 35)) AND (tab0.col4 > 66.87))) AND ((EXISTS { MATCH (in_select_tab0:tab0) WHERE tab0.col0 = in_select_tab0.col3 AND in_select_tab0.col3 < 20 AND in_select_tab0.col1 > 26.56 AND in_select_tab0.col4 < 86.34 OR ((((in_select_tab0.col1 < 67.44)))) AND in_select_tab0.col0 <= 53 AND (in_select_tab0.col3 >= 14 AND in_select_tab0.col3 > 38 AND in_select_tab0.col0 > 75 OR in_select_tab0.col0 > 36 AND (in_select_tab0.col4 <= 17.80) OR ((EXISTS { MATCH (in_select_tab0:tab0) WHERE in_select_tab0.col1 = in_select_tab0.col4 AND ((in_select_tab0.col3 >= 14) OR ((in_select_tab0.col0 <= 71 AND (in_select_tab0.col4 IS Null OR in_select_tab0.col0 < 72) AND in_select_tab0.col4 < 89.39)) AND in_select_tab0.col1 = 61.81 AND (in_select_tab0.col1 >= 89.37 AND in_select_tab0.col1 <= 57.96) AND in_select_tab0.col3 < 42) }) AND in_select_tab0.col1 <= 78.40 AND in_select_tab0.col3 = 75)) AND ((in_select_tab0.col0 >= 72)) OR in_select_tab0.col4 < 39.68 })) AND (tab0.col1 = 63.59 OR tab0.col4 > 25.89) AND ((tab0.col3 < 83 AND tab0.col0 IS Null AND (tab0.col3 < 87) OR tab0.col0 > 15 AND ((tab0.col4 >= 97.66 AND tab0.col3 = 10 OR (tab0.col4 <= 74.4 AND tab0.col4 > 54.40 AND tab0.col1 < 69.0 AND tab0.col0 <= 80) OR (tab0.col3 > 38 OR (tab0.col4 = 10.85 OR tab0.col4 = 92.51 OR tab0.col4 = 56.3 OR tab0.col4 = 64.97 OR tab0.col4 = 46.59 OR tab0.col4 = 24.40)) OR ((tab0.col1 <= 38.54 AND (tab0.col4 > 14.87 OR tab0.col1 < 24.66 AND tab0.col3 < 53) OR (tab0.col0 = 15 OR tab0.col0 = 67 OR tab0.col0 = 85 OR tab0.col0 = 28) OR (tab0.col0 >= 4 AND tab0.col0 <= 56) OR (tab0.col3 = 2 OR tab0.col3 = 89) AND tab0.col0 >= 48) AND tab0.col3 > 9 OR (tab0.col0 >= 71)) OR (tab0.col1 < 31.10)) AND (tab0.col4 > 54.76) AND tab0.col1 > 70.24 AND tab0.col4 <= 23.49 OR tab0.col4 >= 10.51 AND tab0.col4 IS Null OR ((tab0.col0 > 18)) AND (tab0.col3 >= 21) OR ((tab0.col3 >= 0) AND (tab0.col0 = 97 OR tab0.col0 = 67)) OR ((tab0.col0 = 85 OR tab0.col0 = 28 OR tab0.col0 = 39 OR tab0.col0 = 7 OR tab0.col0 = 74 OR tab0.col0 = 84)) AND (((tab0.col0 > 9))) AND tab0.col3 < 61 AND (((tab0.col0 >= 5 AND tab0.col0 <= 20) AND tab0.col3 >= 43 AND tab0.col0 >= 59)) AND tab0.col4 > 12.81 AND tab0.col0 > 5) AND ((tab0.col4 > 81.62) AND (tab0.col0 <= 65)) AND ((tab0.col0 <= 30)) AND tab0.col4 <= 15.61 AND (((((tab0.col0 > 91 OR (tab0.col3 < 71 OR (((tab0.col0 = 61 OR tab0.col0 = 92 OR tab0.col0 = 44 OR tab0.col0 = 68 OR tab0.col0 = 74) AND tab0.col1 > 14.73 AND tab0.col0 < 98 OR EXISTS { MATCH (in_select_tab0:tab0) WHERE tab0.col0 = in_select_tab0.col3 AND in_select_tab0.col3 IS Null } AND ((tab0.col1 > 51.67))))))) OR (tab0.col4 >= 49.53) OR tab0.col0 < 50 OR tab0.col4 > 80.44)))) AND tab0.col3 >= 45 AND (tab0.col0 > 35) OR (tab0.col4 < 36.0 OR (tab0.col4 >= 69.73))))) AND (((tab0.col3 > 83))) AND tab0.col0 = 85 AND ((((((tab0.col0 < 78)))) AND ((tab0.col0 >= 92 OR (((tab0.col0 >= 54))))) OR (tab0.col1 > 27.17) AND tab0.col3 > 69 AND (tab0.col0 >= 99) OR (tab0.col0 IS Null) AND tab0.col3 > 27)) AND (tab0.col3 = 6 OR tab0.col3 = 2 OR tab0.col3 = 2 OR tab0.col3 = 56 OR tab0.col3 = 39) AND (tab0.col0 > 84) AND tab0.col3 < 87 AND (tab0.col3 >= 56) OR (tab0.col3 > 48) AND (tab0.col4 < 84.3) OR tab0.col1 > 7.22 RETURN tab0.pk;
```
If I find any smaller queries I'll update this issue. Most of the queries I've found that cause a segfault are massive. 

The table structure for the above queries:
```
CREATE NODE TABLE tab0(ID SERIAL,pk INT32, col0 INT32, col1 FLOAT, col2 STRING, col3 INT32, col4 FLOAT, col5 STRING, PRIMARY KEY(ID));
```

**Comment by ray6080** [comment] 2024-09-02 04:07
I cannot reproduce this now on master. Closing for now.

**Closed by ray6080** 2024-09-02 04:07 UTC
Labels: bug
