### ISSUE TITLE
Failed to load parquet with large string column type

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1917] opened 2023-08-10 19:20 UTC
Our string representation doesn't not differentiate string/large string we should be able to load large string column as a regular string column. A switch case is missing at this point.

**Comment by prrao87** [comment] 2023-08-10 20:11
Here's an MRE to help diagnose/debug this issue further. The issue I'm facing only appears when we use parquet files that were written by Polars. The Polars [docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_parquet.html) clearly state that if the `use_pyarrow=True` kwarg is used during export, it uses the C++ implementation of arrow, which should be the same implementation on which duckdb and kuzudb depend. So that's what I'm using here in this example.
 
### Data

Say I have some input CSV data that I want to compress and store in parquet (for scalability reasons downstream)

```
id,name,gender,birthday,age,isMarried
1,Kenneth Scott,male,1984-04-14,39,true
2,Stephanie Lozano,female,1993-12-31,29,true
3,Thomas Williams,male,1979-02-09,44,true
4,Christopher Hill,male,1976-11-08,46,false
5,Robert Gill,male,1991-05-16,32,true
```

### Export CSV as parquet
I can easily read this csv into duckdb and convert it to a polars dataframe (assuming polars is installed). I realize that I  can use duckdb to directly output a parquet file here in this simple example. However, in a real case, I'd have data coming in from an upstream ETL data pipeline that uses polars to pre-process the data in various ways, which I'm trying to replicate with this example.

```py
import duckdb

conn = duckdb.connect(database=":memory:", read_only=False)

df = conn.query("SELECT * from 'persons.csv'").pl()
df.write_parquet("persons.parquet", use_pyarrow=True)
```

This writes out a parquet file that conforms to the C++ implementation of arrow, despite polars using arrow2 for other areas of its workflow.

### Read parquet and verify `pyarrow` data types

The data that we just exported to parquet can be read back into duckdb, converted to an arrow table, whose data types we can verify were specified correctly (name and gender are of type `string` as we expect).

```py
import duckdb

conn = duckdb.connect(database=":memory:", read_only=False)

tbl = conn.query("SELECT * FROM 'persons.parquet'").to_arrow_table()
print(tbl)
```
It's clear that the `pyarrow` data types are as expected (string, date, int and bool).

```
pyarrow.Table
id: int64
name: string
gender: string
birthday: date32[day]
age: int64
isMarried: bool
----
id: [[1,2,3,4,5]]
name: [["Kenneth Scott","Stephanie Lozano","Thomas Williams","Christopher Hill","Robert Gill"]]
gender: [["male","female","male","male","male"]]
birthday: [[1984-04-14,1993-12-31,1979-02-09,1976-11-08,1991-05-16]]
age: [[39,29,44,46,32]]
isMarried: [[true,true,true,false,true]]
```

### Attempt to read parquet into Kuzu

This parquet file we just exported can be read into Kuzu (as per the docs) as follows:

```py
import kuzu

# Create database
db = kuzu.Database("./persons")
conn = kuzu.Connection(db)

# Create tables
conn.execute(
    """
    CREATE NODE TABLE
        Person(
            id INT64,
            name STRING,
            gender STRING,
            birthday DATE,
            age INT32,
            isMarried BOOLEAN,
            PRIMARY KEY (id)
        )
    """
)

# Insert parquet into node table
conn.execute(f"COPY Person FROM 'persons.parquet'")
```
This doesn't work as intended.

```
Traceback (most recent call last):
  File "/Users/prrao/code/kuzudb-study/data/import.py", line 39, in <module>
    conn.execute(f"COPY Person FROM 'persons.parquet'")
  File "/Users/prrao/.pyenv/versions/3.11.2/lib/python3.11/site-packages/kuzu/connection.py", line 88, in execute
    self._connection.execute(
RuntimeError: InMemColumnChunkWithOverflow::copyArrowArray
```

### Uncovering the root of the error

It would be helpful to diagnose the source of the error, and maybe identify a potential workaround, or print a more helpful error message to help the user understand what to do. Currently, the only way I can think of to sidestep the problem is to do the whole thing in duckdb, but in a real situation that may not be possible, which is why I'd like to see if this is something that can be worked around on Kuzu's end (rather than posting an issue in the polars repo). Any help in diagnosing this error further would be appreciated!

**Comment by acquamarin** [comment] 2023-08-15 16:04
Hi Prashanth,
We have added support to load parquet large string in the #1929. You can try to load your parquet file using the latest master.

Thanks,

Ziyi

**Comment by prrao87** [comment] 2023-08-16 01:23
I'll take a look at this as soon as I can, thanks @acquamarin!

**Comment by prrao87** [comment] 2023-08-21 14:02
This  works great as per my tests in `0.7.0`! I think we can close it.

**Closed** 2023-09-07 06:43 UTC
